name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: git clone
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run ci
    - run: npm run eslint
    - run: npm run test  
    - run: npm run build 

  # deploy: 

  #   needs: [build]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: SSH and deploy
  #     uses: appleboy/ssh-action@master
  #   with: 
  #     host: ${{ secrets.SSH_HOST }}
  #     username: ${{ secrets.SSH_USERNAME }}
  #     key: ${{ secrets.SSH_KEY }}
  #     port: ${{ secrets.SSH_PORT }}
  #     script: |
  #         cd www/mywarehouse
  #         git pull origin master
  #         npm i --production
  #         pm2 restart node-app


